name: label pr

on: 
  pull_request:
    types: [opened, reopened]

jobs:
  run-my-action:
    name: label pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          name: 'Hax'
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          label: 'needs-review'
