name: label-pr

on:
  pull_request:
    types: 
      - opened
      - reopened
      - closed

jobs:
  add-label:
    name: label-pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          name: "Hax"
          gh-token: ${{ secrets.GITHUB_TOKEN }}
